version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.13
        user: root
    working_directory: /src
    steps:
      - checkout
      - setup_remote_docker
      - run: ./ci/build_image.sh
      - run: ./ci/run_tests.sh
      - deploy:
          name: Push the latest image to Docker Hub
          command: |
            if [ -n "${CIRCLE_BUILD_NUM}" ] && [ -z "${CIRCLE_PR_NUM}" ] && [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./ci/deploy.sh
            fi
